### ISSUE TITLE
ValueError: All arrays must be of the same length

### ISSUE THREAD

**Issue by MrCreepyCraft32** [AffectAnalysisGroup/PyAFAR#4]
I followed the steps and installed PyAFAR CPU on a virtual environment as recommended in the wiki.

After specifying a videos folder and an output folder, here are the logs I get when starting the process :
```
C:\Users\theot\.conda\envs\pyafar\lib\site-packages\PyAFAR_GUI\models
['au_1', 'au_2', 'au_3', 'au_4', 'au_6', 'au_9', 'au_12', 'au_20', 'au_28']
D:/Windows/Bureau/videos\data_src_bck.mp4
True
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Length of video
656
cannot unpack non-iterable NoneType object
cannot unpack non-iterable NoneType object
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\theot\.conda\envs\pyafar\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\theot\.conda\envs\pyafar\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\theot\.conda\envs\pyafar\lib\site-packages\PyAFAR_GUI\__init__.py", line 195, in process_file
    df = pd.DataFrame.from_dict(cv)
  File "C:\Users\theot\.conda\envs\pyafar\lib\site-packages\pandas\core\frame.py", line 1760, in from_dict
    return cls(data, index=index, columns=columns, dtype=dtype)
  File "C:\Users\theot\.conda\envs\pyafar\lib\site-packages\pandas\core\frame.py", line 709, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "C:\Users\theot\.conda\envs\pyafar\lib\site-packages\pandas\core\internals\construction.py", line 481, in dict_to_mgr
    return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)
  File "C:\Users\theot\.conda\envs\pyafar\lib\site-packages\pandas\core\internals\construction.py", line 115, in arrays_to_mgr
    index = _extract_index(arrays)
  File "C:\Users\theot\.conda\envs\pyafar\lib\site-packages\pandas\core\internals\construction.py", line 655, in _extract_index
    raise ValueError("All arrays must be of the same length")
ValueError: All arrays must be of the same length
```

**Comment by Ntweat** [comment]
Can you verify if there are faces in the source video.
The log looks like there were no faces and it tried to convert an empty dictionary to dataframe. 

Additionally you can try the [Python interface](https://github.com/AffectAnalysisGroup/PyAFAR/wiki/4.-How-to-use#python-interface) and check if the length of all the columns in the dictionary are same. 

Let us know if you have any further issues / questions

**Comment by MrCreepyCraft32** [comment]
I am sure there are faces in the source video

I was using the infant mode, I tried the adult mode:
```
C:\Users\theot\.conda\envs\pyafar\lib\site-packages\PyAFAR_GUI\models
['au_1', 'au_2', 'au_4', 'au_6', 'au_7', 'au_10', 'au_12', 'au_14', 'au_15', 'au_17', 'au_23', 'au_24']
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\theot\.conda\envs\pyafar\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\theot\.conda\envs\pyafar\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\theot\.conda\envs\pyafar\lib\site-packages\PyAFAR_GUI\__init__.py", line 206, in process_adult
    import PyAFAR_GUI.adult_afar as sn
  File "C:\Users\theot\.conda\envs\pyafar\lib\site-packages\PyAFAR_GUI\adult_afar.py", line 21, in <module>
    facenet_model = tf.keras.models.load_model(facenet_model_path)
  File "C:\Users\theot\.conda\envs\pyafar\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\theot\.conda\envs\pyafar\lib\site-packages\keras\utils\generic_utils.py", line 857, in func_load
    code = marshal.loads(raw_code)
ValueError: bad marshal data (unknown type code)
```

**Comment by Ntweat** [comment]
`    code = marshal.loads(raw_code)
ValueError: bad marshal data (unknown type code)`

Indicates that the steps were not correctly followed. This is an error in python 3.9 and above. 
PyAFAR works with python 3.7

**Comment by MrCreepyCraft32** [comment]
> `    code = marshal.loads(raw_code)
> ValueError: bad marshal data (unknown type code)`
> 
> Indicates that the steps were not correctly followed. This is an error in python 3.9 and above. 
> PyAFAR works with python 3.7 
> 
> 

I wasn't able to install PyAFAR using Python 3.7
When trying the pip install command, I get an error. Every time I do, I get a different error, but I never get it to work
Only managed to get no fatal errors using Python 3.8.0

**Comment by Ntweat** [comment]
PyAFAR has been tested only on Python 3.7 

The error is known for newer Python versions. 

Did you follow all the steps in the installation step? Using Conda? installed cmake? Dlib ?

**Comment by MrCreepyCraft32** [comment]
> PyAFAR has been tested only on Python 3.7 
> 
> The error is known for newer Python versions. 
> 
> Did you follow all the steps in the installation step? Using Conda? installed cmake? Dlib ? 
> 
> 

I did, the only errors I got were in the pip install command
I also figured out that `conda install conda-forge:dlib` wasn't working, I found a workaround : `conda install -c conda-forge dlib`

**Comment by Ntweat** [comment]
glad it worked in the end.! Thank you for letting us know the work around.
